version: '3'

services:
  postgres1:
    image: postgres:12
    environment:
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: pass1
      POSTGRES_DB: source_db1
    ports:
      - "5433:5432"

  postgres2:
    image: postgres:12
    environment:
      POSTGRES_USER: user2
      POSTGRES_PASSWORD: pass2
      POSTGRES_DB: source_db2
    ports:
      - "5434:5432"

  dwh:
    image: postgres:12
    environment:
      POSTGRES_USER: dwh_user
      POSTGRES_PASSWORD: dwh_pass
      POSTGRES_DB: dwh_db
    ports:
      - "5435:5432"

  airflow:
    image: puckel/docker-airflow
    restart: always
    environment:
      - LOAD_EX=n
      - EXECUTOR=SequentialExecutor
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/usr/local/airflow/dags
